apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: arn:aws:s3:::demo-k8s-cka
    fstype: ext4

