apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  imagePullSecrets:
    - name: private-reg-cred #kubectl create secret docker-registry private-reg-cred \
                    #--docker-server=myprivateregistry.com:5000 \
                    #--docker-username=dock_user \
                    #--docker-password=dock_password \
                    #--docker-email=dock_user@myprivateregistry.com

