---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBN
    QTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJD
    Z0tDQVFFQTJ3MWQrTGtTWWIwc1g5S2Nzc285MlFOMnZrbjV5Q0tVaDhzNzJxOTFjUk14ClArZTlq
    a2UrZjdlazlEbmg2Z2w3Wi9MMWpCR2pjTWRZZEZDU0tMMzdJMXZVNjBCczBTT25nS0hJTjNNNWRE
    TTgKdnVxWkR3azl6dkcveDg3VlpMT3NnU2kraFVSeEVSRUtOM0M2YXhtak1halBCZlkvZDVqSkY5
    R29ldms3UHBmNwpDQldDbTJaQ29CWHcwUzdWMk9TRklpZGRyTkhEeGtOTG9DVEliTkxLSGluYStS
    THlBaFZ6YjFHMWo1N3RXNDRuCm1LK3pLMVFidHRIc2NERWhsNVBJQ3BMM1gySWUyNzRuY0R6YS9n
    eThJdXBVb1NJdHAwMG5KR2VlWkFSb3dQYmoKVm9ldzFvWENpclB6ZmEzSmZqK0dOa0JMY1ZGMUJW
    RzVmK3Q2aVJFZ2l3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRU15NU1xL2xy
    djNHV201R1B4cGQyUG1SZ295ZmprSmU2bFpPdjF0T2RqZDVZK2MxbXROCmoxUkFYc3dNdUswVjRj
    VmFEVUpnK0t1eldjbUY2TkxiNThqaDVOUGwrbnVReEp4NHk3MEVJVjR5TTJ0Qk13bUMKWFdDNktU
    bTMxcDVaaUlmNEhLVTJRYjFMZEtEaXh4YWtUQUgwT0RLUFhJWVVOdkVtaTVsenZDTDJ0MUpwaUpz
    aApsKzBFS0EwM2JkbEppcE5hbzFLVHFvMTRGOTJ3azFJR251aDJvUEczUTZFaUJsYkhzZXFzZlpE
    b1NoTFhpaUtjCksrTjNoS0lhc0xDcDVJQ0MyT09ROEdWeHIzcS9oSldjQW9TcG5zSVpkSHA0NnQ0
    ZXA2YzVUOTl5djVXdTYvbVMKWlB1ZENlTGFMSnlZS25qV0x1ZFFXMHNrbHlUaGJMcVQyYWc9Ci0t
    LS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth